# Подготовка среды
# FROM brunneis/python:3.8.3-ubuntu-20.04 AS python_env
FROM python:3.8
WORKDIR /app
ADD . /app

ARG DB_ADDRESS

COPY poetry.lock pyproject.toml /app/

RUN pip install poetry
RUN poetry install

ENV PYTHONPATH "${PYTHONPATH}:/app"

ENTRYPOINT ["poetry", "run", "run-server"]